name: 'Generate Vulnerability Alerts CSV File'
description: 'This action generates a csv file that contains a list of the vulnerabilities detected for each of the specified repos.'
branding:
  icon: 'package'
  color: 'green'
inputs: 
  repo-token:
    description: 'REQUIRED: The GITHUB_TOKEN secret. Make sure this token has rights to all the repos you want to catalog.'
    required: true
  org-name:
    description: 'The name of the owner/organization that contains the repositories (defaults to current repository owner)'
    default: ${{ github.repository_owner }}
    required: false
  repo-names:
    description: 'REQUIRED: A comma separated list of repository names to catalog.'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
