on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    name: Genereate a list of dependencies for this repository
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Generate dependencies action
      uses: ./ # Uses an action in the root directory
      with:
        repo-token: ${{ secrets.DEPS_TOKEN }}
        org-name: octodemo
        repo-names: demo-ghas-geekmasher,activemq